import { DashboardStat, HomeworkItem, NoteItem, SubjectItem, LearningToolItem, StudyTaskItem } from "@/types";

export const STUDENT_DASHBOARD_STATS: DashboardStat[] = [
  {
    label: "Pending Tasks",
    value: "04",
    subtext: "2 assignments due this week",
    iconName: "ClipboardList",
    accentColor: "terracotta",
  },
  {
    label: "Notes Available",
    value: "28",
    subtext: "4 new notes uploaded",
    iconName: "BookOpen",
    accentColor: "navy",
  },
  {
    label: "Study Streak",
    value: "05 Days",
    subtext: "Great consistency! Keep it up.",
    iconName: "Flame",
    accentColor: "terracotta",
  },
];

export const STUDENT_TODAYS_LEARNING = {
  subject: "Mathematics",
  chapter: "Chapter 4 — Linear Equations in One Variable",
  topic: "Solving equations with variables on both sides",
  progress: 65,
  estimatedTime: "25 mins",
  resourcesCount: 4,
  actionHref: "/student/notes",
};

export const STUDENT_SUBJECTS: SubjectItem[] = [
  {
    id: "sub-1",
    name: "Mathematics",
    code: "MATH-08",
    color: "#C75A4B",
    iconName: "Calculator",
    resourcesCount: 6,
    grade: "8th Standard",
    teacherName: "Mrs. Reena Thomas",
  },
  {
    id: "sub-2",
    name: "Science",
    code: "SCI-08",
    color: "#2C5D7D",
    iconName: "FlaskConical",
    resourcesCount: 8,
    grade: "8th Standard",
    teacherName: "Mr. Ramesh Kumar",
  },
  {
    id: "sub-3",
    name: "English",
    code: "ENG-08",
    color: "#12324D",
    iconName: "BookOpenText",
    resourcesCount: 5,
    grade: "8th Standard",
    teacherName: "Ms. Stella Joseph",
  },
  {
    id: "sub-4",
    name: "Kannada (ಕನ್ನಡ)",
    code: "KAN-08",
    color: "#C75A4B",
    iconName: "Languages",
    resourcesCount: 4,
    grade: "8th Standard",
    teacherName: "Mrs. Gowri Shankar",
  },
  {
    id: "sub-5",
    name: "Hindi (हिन्दी)",
    code: "HIN-08",
    color: "#6F91A6",
    iconName: "Globe2",
    resourcesCount: 3,
    grade: "8th Standard",
    teacherName: "Mrs. Meenakshi S",
  },
  {
    id: "sub-6",
    name: "Social Science",
    code: "SOC-08",
    color: "#2C5D7D",
    iconName: "Landmark",
    resourcesCount: 7,
    grade: "8th Standard",
    teacherName: "Mr. Anthony Raj",
  },
];

export const STUDENT_UPCOMING_HOMEWORK: HomeworkItem[] = [
  {
    id: "hw-1",
    title: "Exercise 4.2: Word Problems on Linear Equations",
    subject: "Mathematics",
    grade: "8th Standard A",
    dueDate: "Tomorrow, 4:00 PM",
    instructions: "Complete problems 1 to 10 from page 64. Show all working steps clearly in your notebook or upload PDF.",
    status: "PENDING",
    teacherName: "Mrs. Reena Thomas",
    hasAttachment: true,
  },
  {
    id: "hw-2",
    title: "Diagrammatic Explanation of Cell Organelles",
    subject: "Science",
    grade: "8th Standard A",
    dueDate: "Friday, 5:00 PM",
    instructions: "Draw and label Plant Cell vs Animal Cell with concise function descriptions for nucleus and mitochondria.",
    status: "PENDING",
    teacherName: "Mr. Ramesh Kumar",
    hasAttachment: false,
  },
  {
    id: "hw-3",
    title: "Poetry Analysis: The Road Not Taken",
    subject: "English",
    grade: "8th Standard A",
    dueDate: "Monday, 10:00 AM",
    instructions: "Write a 150-word reflection on the metaphorical meaning of choices presented in the poem.",
    status: "PENDING",
    teacherName: "Ms. Stella Joseph",
    hasAttachment: true,
  },
];

export const STUDENT_RECENT_NOTES: NoteItem[] = [
  {
    id: "note-1",
    title: "Linear Equations — Key Formulas & Practice Sheet",
    subject: "Mathematics",
    chapter: "Chapter 4",
    grade: "Class 8A",
    teacherName: "Mrs. Reena Thomas",
    fileSize: "1.4 MB",
    uploadedAt: "Today, 10:30 AM",
    downloadsCount: 26,
  },
  {
    id: "note-2",
    title: "Structure of the Atom & Atomic Models Summary",
    subject: "Science",
    chapter: "Chapter 5",
    grade: "Class 8A",
    teacherName: "Mr. Ramesh Kumar",
    fileSize: "2.1 MB",
    uploadedAt: "Yesterday",
    downloadsCount: 31,
  },
  {
    id: "note-3",
    title: "Grammar Notes: Active & Passive Voice Transformations",
    subject: "English",
    chapter: "Grammar Unit 3",
    grade: "Class 8A",
    teacherName: "Ms. Stella Joseph",
    fileSize: "850 KB",
    uploadedAt: "2 days ago",
    downloadsCount: 22,
  },
];

export const STUDENT_TODAY_TASKS: StudyTaskItem[] = [
  {
    id: "task-1",
    subject: "Mathematics",
    topic: "Review Linear Equations examples 1-5",
    scheduledDate: "Today",
    durationMinutes: 30,
    completed: true,
  },
  {
    id: "task-2",
    subject: "Science",
    topic: "Read Cell Division chapter summary",
    scheduledDate: "Today",
    durationMinutes: 45,
    completed: false,
  },
  {
    id: "task-3",
    subject: "Kannada",
    topic: "Vocabulary practice for Unit 2",
    scheduledDate: "Today",
    durationMinutes: 20,
    completed: false,
  },
];

export const STUDENT_LEARNING_TOOLS: LearningToolItem[] = [
  {
    id: "tool-1",
    title: "Language Lab",
    description: "Interactive vocabulary, conversational phrases, and grammar in English, Kannada & Hindi.",
    category: "Languages",
    href: "/student/languages",
    iconName: "Languages",
    badge: "3 Languages",
  },
  {
    id: "tool-2",
    title: "Math Solver",
    description: "Step-by-step arithmetic, algebraic expressions, and concept breakdowns with clarity.",
    category: "Mathematics",
    href: "/student/math",
    iconName: "Calculator",
    badge: "Step-by-Step",
  },
  {
    id: "tool-3",
    title: "Study Planner",
    description: "Deterministic daily schedule generator balancing exam dates, study hours, and subjects.",
    category: "Discovery",
    href: "/student/planner",
    iconName: "CalendarClock",
    badge: "Deterministic",
  },
  {
    id: "tool-4",
    title: "Learning Hub",
    description: "Curated science curiosities, general knowledge, study strategies, and wellness insights.",
    category: "Discovery",
    href: "/student/learning",
    iconName: "Compass",
    badge: "Curated",
  },
  {
    id: "tool-5",
    title: "Career Corner",
    description: "Verified scholarship notices, Olympiad deadlines, STEM programs, and future paths.",
    category: "Opportunities",
    href: "/student/opportunities",
    iconName: "Sparkles",
    badge: "Scholarships",
  },
];
